name: JavaScript CI

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run format

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
